# These are supported funding model platforms
# hoping this doesn't count as advertisement, am uncertain
# I feel like in spirit it's exactly the same as a patreon account, just non-recurring, and patreon is natively supported
custom: "https://store.steampowered.com/app/992240/Trawel/"
